name: "Setup Secret"

on:
  'push'

jobs:
  pretest:
    name: Set Secret test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Action
        uses: ./
        with:
            repo: virgil246/secret-manage-action
            token: ${{ secrets.GH_PA_TOKEN }}
            name: 'Your-cookie-name' 
            value: 'Your-cookie-value'
